# Generated by Django 5.0.2 on 2024-02-18 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_n', models.CharField(max_length=30)),
                ('dose', models.IntegerField()),
                ('until', models.DateField()),
                ('dev', models.CharField(max_length=30)),
                ('effect', models.CharField(max_length=100)),
                ('others', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('s_name', models.CharField(max_length=30)),
                ('birth', models.DateField()),
                ('gender', models.CharField(max_length=3)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('role', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_dose', models.IntegerField()),
                ('since', models.DateField()),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
                ('pat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
