# Generated by Django 4.2.6 on 2024-02-19 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recipes_until'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checks',
            options={'verbose_name': 'Чек', 'verbose_name_plural': 'Чеки'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'Лекарство', 'verbose_name_plural': 'Лекарства'},
        ),
        migrations.AlterModelOptions(
            name='recipes',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='checks',
            name='pat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='checks',
            name='sum',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Сумма чека'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dev',
            field=models.CharField(max_length=30, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dose',
            field=models.IntegerField(verbose_name='Дозировка'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='effect',
            field=models.CharField(max_length=100, verbose_name='Эффект'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='med_n',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='others',
            field=models.CharField(max_length=100, verbose_name='Другие аспекты'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='until',
            field=models.DateField(verbose_name='Действительно до'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='m_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicine', verbose_name='Лекарство'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='pat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='r_dose',
            field=models.IntegerField(verbose_name='Дозировка рецепта'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='since',
            field=models.DateField(verbose_name='Начиная с'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='until',
            field=models.DateField(verbose_name='Действительно до'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=3, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=30, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='s_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
    ]
